AllCops:
  Exclude:
    - db/**/*
    - vendor/**/*
    - node_modules/**/*
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/SymbolArray:
  EnforcedStyle: brackets
Metrics/BlockLength:
  Exclude:
    - spec/controllers/events_controller_spec.rb
Layout/LineLength:
  Exclude:
    - config/initializers/devise.rb
Style/ClassAndModuleChildren:
  Exclude:
    - app/controllers/users/*