AllCops:
  Exclude:
    - db/**/*
    - vendor/**/*
    - node_modules/**/*
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/SymbolArray:
  EnforcedStyle: brackets
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/**/*
Layout/LineLength:
  Exclude:
    - config/initializers/devise.rb
Style/ClassAndModuleChildren:
  Enabled: false
Naming/PredicateName:
  Enabled: false